# Generated by Django 5.0.2 on 2024-10-13 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_login', '0002_rename_usuarios_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='Nome',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
