# Generated by Django 5.0.2 on 2024-10-13 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_login', '0003_usuario_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='Nome',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
